CREATE SCHEMA agent;
GRANT USAGE ON SCHEMA agent TO brf;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA agent TO brf;
ALTER DEFAULT PRIVILEGES IN SCHEMA agent GRANT ALL PRIVILEGES ON TABLES TO brf;